#/bin/bash
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.aa
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ab
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ac
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ad
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ae
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.af
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ag
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ah
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ai
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.aj
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ak
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.al
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.am
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.an
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ao
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ap
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.aq
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ar
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.as
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.at
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.au
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.av
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.aw
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ax
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ay
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.az
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ba
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bb
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bc
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bd
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.be
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bf
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bg
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bh
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bi
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bj
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bk
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bl
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bm
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bn
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bo
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bp
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bq
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.br
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bs
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bt
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bu
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bv
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bw
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bx
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.by
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.bz
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ca
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cb
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cc
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cd
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ce
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cf
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cg
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ch
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ci
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cj
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ck
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cl
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cm
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cn
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.co
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cp
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cq
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cr
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cs
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ct
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cu
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cv
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cw
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cx
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cy
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.cz
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.da
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.db
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dc
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dd
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.de
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.df
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dg
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dh
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.di
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dj
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dk
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dl
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dm
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dn
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.do
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dp
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dq
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dr
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ds
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dt
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.du
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dv
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dw
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dx
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dy
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.dz
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ea
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.eb
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ec
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ed
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ee
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ef
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.eg
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.eh
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ei
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ej
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ek
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.el
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.em
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.en
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.eo
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ep
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.eq
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.er
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.es
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.et
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.eu
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ev
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ew
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ex
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ey
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ez
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fa
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fb
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fc
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fd
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fe
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ff
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fg
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fh
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fi
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fj
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fk
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fl
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fm
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fn
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fo
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fp
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fq
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fr
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fs
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ft
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fu
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fv
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fw
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fx
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fy
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.fz
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ga
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gb
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gc
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gd
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ge
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gf
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gg
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gh
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gi
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gj
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gk
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gl
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gm
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gn
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.go
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gp
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gq
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gr
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gs
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gt
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gu
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gv
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gw
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gx
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gy
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.gz
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ha
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hb
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hc
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hd
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.he
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hf
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hg
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hh
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hi
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hj
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hk
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hl
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hm
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hn
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ho
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hp
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hq
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hr
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hs
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ht
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hu
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hv
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hw
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hx
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hy
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.hz
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ia
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ib
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ic
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.id
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ie
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.if
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ig
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ih
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ii
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ij
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ik
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.il
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.im
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.in
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.io
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ip
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.iq
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ir
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.is
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.it
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.iu
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.iv
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.iw
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ix
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.iy
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.iz
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ja
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jb
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jc
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jd
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.je
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jf
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jg
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jh
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ji
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jj
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jk
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jl
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jm
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jn
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jo
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jp
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jq
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jr
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.js
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jt
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ju
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jv
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jw
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jx
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jy
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.jz
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.ka
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.kb
wget https://grunt.sefsc.noaa.gov/parr/SEAMAPD21.tar.gz.kc